repos:
  - repo: git@github.com:rbubley/mirrors-prettier.git
    rev: v3.9.9
    hooks:
      - id: prettier
        args: [--prose-wrap, preserve]
        types: [markdown]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.3
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/lycheeverse/lychee
    rev: v0.15.1
    hooks:
      - id: lychee-docker
        args: [--offline]
  - repo: git@github.com:jvanlier/recall
    rev: 92cdac1c5647dff306462d4c518b2d9c20e3b38e
    hooks:
      - id: recall-check
